// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy_4NuWesBjSNZ6-UJ-Ng-J81VuaOfWEw',
    appId: '1:1081036736225:web:eff0a7775982f130df59a0',
    messagingSenderId: '1081036736225',
    projectId: 'rento-aryan21',
    authDomain: 'rento-aryan21.firebaseapp.com',
    storageBucket: 'rento-aryan21.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7ojKfK0DVg12FqMdR3U_x4wYpxRa6Jmc',
    appId: '1:1081036736225:android:621369754ac7428bdf59a0',
    messagingSenderId: '1081036736225',
    projectId: 'rento-aryan21',
    storageBucket: 'rento-aryan21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3xL4v3khfZCZptOxKN-2TxL7u6egOlj0',
    appId: '1:1081036736225:ios:a92a6161dcc6ad48df59a0',
    messagingSenderId: '1081036736225',
    projectId: 'rento-aryan21',
    storageBucket: 'rento-aryan21.firebasestorage.app',
    iosBundleId: 'com.example.rento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3xL4v3khfZCZptOxKN-2TxL7u6egOlj0',
    appId: '1:1081036736225:ios:a92a6161dcc6ad48df59a0',
    messagingSenderId: '1081036736225',
    projectId: 'rento-aryan21',
    storageBucket: 'rento-aryan21.firebasestorage.app',
    iosBundleId: 'com.example.rento',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy_4NuWesBjSNZ6-UJ-Ng-J81VuaOfWEw',
    appId: '1:1081036736225:web:db687217932b01eddf59a0',
    messagingSenderId: '1081036736225',
    projectId: 'rento-aryan21',
    authDomain: 'rento-aryan21.firebaseapp.com',
    storageBucket: 'rento-aryan21.firebasestorage.app',
  );
}
